"""record descriptions and classifications on snapshots

Revision ID: 10293ca40da5
Revises: 6bd7794502e7
Create Date: 2026-08-24 00:17:54.056062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10293ca40da5'
down_revision: Union[str, Sequence[str], None] = '6bd7794502e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot_income_entries', sa.Column('description', sa.String(), nullable=True))
    op.add_column('snapshot_outgoing_entries', sa.Column('description', sa.String(), nullable=True))
    op.add_column('snapshot_outgoing_entries', sa.Column('display_category', sa.String(), nullable=True))
    op.add_column('snapshot_outgoing_entries', sa.Column('outgoing_treatment', sa.String(), nullable=True))
    op.add_column('snapshot_outgoing_entries', sa.Column('classification_source', sa.String(), nullable=True))
    op.add_column('snapshot_outgoing_entries', sa.Column('taxonomy_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshot_outgoing_entries', 'taxonomy_version')
    op.drop_column('snapshot_outgoing_entries', 'classification_source')
    op.drop_column('snapshot_outgoing_entries', 'outgoing_treatment')
    op.drop_column('snapshot_outgoing_entries', 'display_category')
    op.drop_column('snapshot_outgoing_entries', 'description')
    op.drop_column('snapshot_income_entries', 'description')
    # ### end Alembic commands ###
