"""add outgoing classification

Revision ID: 6bd7794502e7
Revises: 819c4c796c60
Create Date: 2026-08-23 14:39:58.537086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd7794502e7'
down_revision: Union[str, Sequence[str], None] = '819c4c796c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_classification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('normalized_description', sa.String(), nullable=False),
    sa.Column('display_category', sa.String(), nullable=False),
    sa.Column('outgoing_treatment', sa.String(), nullable=False),
    sa.Column('taxonomy_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'normalized_description', name='uq_preference_customer_description')
    )
    op.create_index(op.f('ix_customer_classification_preferences_customer_id'), 'customer_classification_preferences', ['customer_id'], unique=False)
    op.add_column('editable_statement_entries', sa.Column('display_category', sa.String(), nullable=True))
    op.add_column('editable_statement_entries', sa.Column('outgoing_treatment', sa.String(), nullable=True))
    op.add_column('editable_statement_entries', sa.Column('classification_source', sa.String(), nullable=True))
    op.add_column('editable_statement_entries', sa.Column('taxonomy_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('editable_statement_entries', 'taxonomy_version')
    op.drop_column('editable_statement_entries', 'classification_source')
    op.drop_column('editable_statement_entries', 'outgoing_treatment')
    op.drop_column('editable_statement_entries', 'display_category')
    op.drop_index(op.f('ix_customer_classification_preferences_customer_id'), table_name='customer_classification_preferences')
    op.drop_table('customer_classification_preferences')
    # ### end Alembic commands ###
