"""add editable financial statement

Revision ID: 819c4c796c60
Revises: b37fec2203f4
Create Date: 2026-08-22 16:56:58.195530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819c4c796c60'
down_revision: Union[str, Sequence[str], None] = 'b37fec2203f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editable_financial_statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('statement_period', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_account_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('accessible_savings', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('protected_reserve', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('known_arrears', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.CheckConstraint('accessible_savings >= 0', name='ck_editable_accessible_savings_non_negative'),
    sa.CheckConstraint('known_arrears >= 0', name='ck_editable_known_arrears_non_negative'),
    sa.CheckConstraint('protected_reserve >= 0', name='ck_editable_protected_reserve_non_negative'),
    sa.CheckConstraint('version >= 1', name='ck_editable_statement_version_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'statement_period', name='uq_editable_statement_customer_period')
    )
    op.create_index(op.f('ix_editable_financial_statements_customer_id'), 'editable_financial_statements', ['customer_id'], unique=False)
    op.create_table('editable_statement_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('entry_key', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('original_frequency', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('original_amount >= 0', name='ck_editable_entry_amount_non_negative'),
    sa.ForeignKeyConstraint(['statement_id'], ['editable_financial_statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editable_statement_entries_statement_id'), 'editable_statement_entries', ['statement_id'], unique=False)
    op.create_table('editable_statement_expected_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('entry_key', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('original_frequency', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('original_amount >= 0', name='ck_editable_change_amount_non_negative'),
    sa.ForeignKeyConstraint(['statement_id'], ['editable_financial_statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editable_statement_expected_changes_statement_id'), 'editable_statement_expected_changes', ['statement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_editable_statement_expected_changes_statement_id'), table_name='editable_statement_expected_changes')
    op.drop_table('editable_statement_expected_changes')
    op.drop_index(op.f('ix_editable_statement_entries_statement_id'), table_name='editable_statement_entries')
    op.drop_table('editable_statement_entries')
    op.drop_index(op.f('ix_editable_financial_statements_customer_id'), table_name='editable_financial_statements')
    op.drop_table('editable_financial_statements')
    # ### end Alembic commands ###
