"""create core financial-health schema

Revision ID: 878c7c42474b
Revises: 
Create Date: 2026-08-22 04:14:30.860304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '878c7c42474b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confirmed_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('statement_period', sa.Date(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculation_policy_version', sa.String(), nullable=False),
    sa.Column('normalized_monthly_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('normalized_monthly_outgoings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_headroom', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('result_code', sa.String(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supersedes_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('normalized_monthly_income >= 0', name='ck_snapshot_income_non_negative'),
    sa.CheckConstraint('normalized_monthly_outgoings >= 0', name='ck_snapshot_outgoings_non_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['supersedes_snapshot_id'], ['confirmed_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirmed_snapshots_customer_id'), 'confirmed_snapshots', ['customer_id'], unique=False)
    op.create_table('snapshot_income_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('original_frequency', sa.String(), nullable=False),
    sa.Column('normalized_monthly_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('original_amount >= 0', name='ck_income_entry_amount_non_negative'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['confirmed_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshot_income_entries_snapshot_id'), 'snapshot_income_entries', ['snapshot_id'], unique=False)
    op.create_table('snapshot_outgoing_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('original_frequency', sa.String(), nullable=False),
    sa.Column('normalized_monthly_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('original_amount >= 0', name='ck_outgoing_entry_amount_non_negative'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['confirmed_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshot_outgoing_entries_snapshot_id'), 'snapshot_outgoing_entries', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshot_outgoing_entries_snapshot_id'), table_name='snapshot_outgoing_entries')
    op.drop_table('snapshot_outgoing_entries')
    op.drop_index(op.f('ix_snapshot_income_entries_snapshot_id'), table_name='snapshot_income_entries')
    op.drop_table('snapshot_income_entries')
    op.drop_index(op.f('ix_confirmed_snapshots_customer_id'), table_name='confirmed_snapshots')
    op.drop_table('confirmed_snapshots')
    op.drop_table('customers')
    # ### end Alembic commands ###
