"""add correction reason and single successor

Revision ID: 8d271b25c24f
Revises: f1a433fcfbd3
Create Date: 2026-08-24 01:39:18.472930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d271b25c24f'
down_revision: Union[str, Sequence[str], None] = 'f1a433fcfbd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmed_snapshots', sa.Column('correction_reason', sa.String(), nullable=True))
    op.create_unique_constraint('uq_snapshot_single_successor', 'confirmed_snapshots', ['supersedes_snapshot_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_snapshot_single_successor', 'confirmed_snapshots', type_='unique')
    op.drop_column('confirmed_snapshots', 'correction_reason')
    # ### end Alembic commands ###
