"""add resilience fields to confirmed snapshots

Revision ID: b37fec2203f4
Revises: 878c7c42474b
Create Date: 2026-08-22 13:52:16.570567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b37fec2203f4'
down_revision: Union[str, Sequence[str], None] = '878c7c42474b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmed_snapshots', sa.Column('current_account_balance', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('confirmed_snapshots', sa.Column('accessible_savings', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('confirmed_snapshots', sa.Column('protected_reserve', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('confirmed_snapshots', sa.Column('known_arrears', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('confirmed_snapshots', sa.Column('savings_above_reserve', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('confirmed_snapshots', sa.Column('reserve_gap', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('confirmed_snapshots', sa.Column('resilience_result_code', sa.String(), nullable=True))
    op.add_column(
        'confirmed_snapshots',
        sa.Column(
            'resilience_warnings',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.create_check_constraint('ck_snapshot_accessible_savings_non_negative', 'confirmed_snapshots', 'accessible_savings >= 0')
    op.create_check_constraint('ck_snapshot_known_arrears_non_negative', 'confirmed_snapshots', 'known_arrears >= 0')
    op.create_check_constraint('ck_snapshot_protected_reserve_non_negative', 'confirmed_snapshots', 'protected_reserve >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_snapshot_protected_reserve_non_negative', 'confirmed_snapshots', type_='check')
    op.drop_constraint('ck_snapshot_known_arrears_non_negative', 'confirmed_snapshots', type_='check')
    op.drop_constraint('ck_snapshot_accessible_savings_non_negative', 'confirmed_snapshots', type_='check')
    op.drop_column('confirmed_snapshots', 'resilience_warnings')
    op.drop_column('confirmed_snapshots', 'resilience_result_code')
    op.drop_column('confirmed_snapshots', 'reserve_gap')
    op.drop_column('confirmed_snapshots', 'savings_above_reserve')
    op.drop_column('confirmed_snapshots', 'known_arrears')
    op.drop_column('confirmed_snapshots', 'protected_reserve')
    op.drop_column('confirmed_snapshots', 'accessible_savings')
    op.drop_column('confirmed_snapshots', 'current_account_balance')
    # ### end Alembic commands ###
