"""add confirmation idempotency keys

Revision ID: f1a433fcfbd3
Revises: 10293ca40da5
Create Date: 2026-08-24 00:20:14.747413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a433fcfbd3'
down_revision: Union[str, Sequence[str], None] = '10293ca40da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmation_idempotency_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('request_fingerprint', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['confirmed_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'idempotency_key', name='uq_idempotency_customer_key')
    )
    op.create_index(op.f('ix_confirmation_idempotency_keys_customer_id'), 'confirmation_idempotency_keys', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confirmation_idempotency_keys_customer_id'), table_name='confirmation_idempotency_keys')
    op.drop_table('confirmation_idempotency_keys')
    # ### end Alembic commands ###
